### ISSUE TITLE
Integration tests support

### ISSUE THREAD

**Issue by RazrFalcon** [matklad/cov-mark#2]
I'm not sure why it doesn't supported. Shouldn't global names be available to the tests?

**Comment by matklad** [comment]
The "name" here is the linker's symbol. At the moment we make sure that you only get weird mark symbols in you binary if the code is compiled with `#[cfg(test)]`. For integration tests, the code is compiled *without* `#[cfg(test)]`. Alternative designs include:

* just always provide the symbols / incure runtime cost on hitting the mark
* make it possible for the user to choose via feature flag/env var/altentive api (`cov_mark::hit(my_mark, link-in)` or something along those line).

**Comment by RazrFalcon** [comment]
Looks like we have to wait for https://github.com/rust-lang/cargo/issues/2911

But for now, a custom feature would be nice. Because any runtime cost is no go for me.

**Comment by matklad** [comment]
Yeah, given this set of tradoffs, I feel like "make the test into a unit-test" is probably the least bad solution. 

Though, this is biased by rust-analyzer perspective, where all our tests are unit.

**Comment by RazrFalcon** [comment]
In my case, tests can easily reach 2-3 KLOC per module and I don't to fill sources with them.

I will try converting some specific tests to unit one.

**Comment by RazrFalcon** [comment]
So I've ended up using unit testing. So this is not longer an issue for me.

**Comment by matklad** [comment]
I've found my self needing cross-crate coverage mark in rust-analyzer several times, so I implemented that in 2.0-pre.1: https://github.com/matklad/cov-mark/pull/14

**Comment by RazrFalcon** [comment]
Nice! Will keep an eye on it.
